<?php

/* 
CREATE TABLE Message(
message_id INT PRIMARY KEY AUTO_INCREMENT,
s_id INT NOT NULL,
r_id INT NOT NULL,
receiver_switch TINYINT ZEROFILL,
FOREIGN KEY(s_id) REFERENCES User(user_id)
ON DELETE CASCADE,
FOREIGN KEY(r_id) REFERENCES User(user_id)
ON DELETE CASCADE
)
 */ 